FerreteriaProMAX02/Models/Venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaProMAX02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
            this.Facturas = new HashSet<Factura>();
            this.Facturas1 = new HashSet<Factura>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idPersona { get; set; }
        public int idEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas1 { get; set; }
        public virtual Persona Persona { get; set; }
    }
}

FerreteriaProMAX02/Controllers/VentasController.cs
using FerreteriaProMAX02.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FerreteriaProMAX02.Controllers
{
    public class VentasController : Controller
    {
        private FerreteriaDBEntities db = new FerreteriaDBEntities();
        private Metodos.Metodos m = new Metodos.Metodos();
        // GET: Ventas
        public ActionResult Index()
        {

                var ventas = db.Ventas.Include(v => v.Empleado).Include(v => v.Persona);
                return View(ventas.ToList());
        }

        // GET: Ventas/Details/5
        public ActionResult Details(int? id)
        {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Venta venta = db.Ventas.Find(id);
                if (venta == null)
                {
                    return HttpNotFound();
                }
                return View(venta);


        }

        // GET: Ventas/Create
        public ActionResult Create()
        {

                ViewBag.idEmpleado = new SelectList(db.Empleadoes, "IdEmpleado", "IdEmpleado");
                ViewBag.idPersona = new SelectList(db.Personas, "idPersona", "Cedula");
                return View();
        }

        // POST: Ventas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdVenta,fecha,idPersona,idEmpleado")] Venta venta)
        {
                if (ModelState.IsValid)
                {
                    db.Ventas.Add(venta);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.idEmpleado = new SelectList(db.Empleadoes, "IdEmpleado", "IdEmpleado", venta.idEmpleado);
                ViewBag.idPersona = new SelectList(db.Personas, "idPersona", "Cedula", venta.idPersona);
                return View(venta);
            

        }

        // GET: Ventas/Edit/5
        public ActionResult Edit(int? id)
        {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Venta venta = db.Ventas.Find(id);
                if (venta == null)
                {
                    return HttpNotFound();
                }
                ViewBag.idEmpleado = new SelectList(db.Empleadoes, "IdEmpleado", "IdEmpleado", venta.idEmpleado);
                ViewBag.idPersona = new SelectList(db.Personas, "idPersona", "Cedula", venta.idPersona);
                return View(venta);
            

        }

        // POST: Ventas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdVenta,fecha,idPersona,idEmpleado")] Venta venta)
        {
                if (ModelState.IsValid)
                {
                    db.Entry(venta).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.idEmpleado = new SelectList(db.Empleadoes, "IdEmpleado", "IdEmpleado", venta.idEmpleado);
                ViewBag.idPersona = new SelectList(db.Personas, "idPersona", "Cedula", venta.idPersona);
                return View(venta);
            

        }

        // GET: Ventas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
            else if (!Session["id"].ToString().Equals("0"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Venta venta = db.Ventas.Find(id);
                if (venta == null)
                {
                    return HttpNotFound();
                }
                return View(venta);
            }
            else
            {
                return RedirectToAction("Login", "Usuario_Login");
            }

        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Venta venta = db.Ventas.Find(id);
                db.Ventas.Remove(venta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult VentaN()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
            else if (!Session["id"].ToString().Equals("0"))
            {
                ViewBag.IdEmpleado = Session["idempleado"];
                ViewBag.IdPago = new SelectList(db.TipoPagoes, "IdPago", "Nombre");
                ViewBag.IdProductoL = new SelectList(db.Productoes, "IdProducto", "Nombre");
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario_Login");
            }

        }

        // POST: Ventas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VentaN([Bind(Include = "IdVenta,fecha,idPersona,idEmpleado")] Venta ventas)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
            else if (!Session["id"].ToString().Equals("0"))
            {
                if (ModelState.IsValid)
                {
                    db.Ventas.Add(ventas);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.IdEmpleado = Session["idempleado"];
                ViewBag.IdPago = new SelectList(db.TipoPagoes, "IdPago", "Nombre");
                ViewBag.IdProductoL = new SelectList(db.Productoes, "IdProducto", "Nombre");
                return View(ventas);
            }
            else
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
        }
        [HttpGet]
        public ActionResult ObtenerClientes()
        {
            return View(db.Personas.ToList());
        }

        [HttpPost]//para buscar clientes
        public ActionResult ObtenerClientes(string txtnombre, string txtappaterno, string txtdni, string txtcliente)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
            else if (!Session["id"].ToString().Equals("0"))
            {
                if (txtnombre == "")
                {
                    txtnombre = "-1";
                }
                if (txtappaterno == "")
                {
                    txtappaterno = "-1";
                }
                if (txtdni == "")
                {
                    txtdni = "-1";
                }
                if (txtcliente == "")
                {
                    txtcliente = "-1";
                }
                Persona objCliente = new Persona();
                objCliente.Codigo = Int32.Parse(txtcliente);
                objCliente.nombre = txtnombre;
                objCliente.Primer_Apellido = txtappaterno;
                objCliente.Cedula = txtdni;

                if (objCliente.Codigo != -1)
                {
                    List<Persona> persona = m.Get0((int)(objCliente.Codigo));
                    return View(persona);
                }
                else if (!objCliente.nombre.ToString().Equals("-1"))
                {
                    List<Persona> persona = m.Get1(objCliente.nombre);
                    return View(persona);
                }
                else if (!objCliente.Primer_Apellido.ToString().Equals("-1"))
                {
                    List<Persona> persona = m.Get3(objCliente.Primer_Apellido);
                    return View(persona);
                }
                else if (!objCliente.Cedula.ToString().Equals("-1"))
                {
                    List<Persona> persona = m.Get2(objCliente.Cedula);
                    return View(persona);
                }
                else
                {
                    return View(db.Personas.ToList());
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario_Login");
            }

        }

        [HttpPost]
        public ActionResult Seleccionar(string idProducto)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Login", "Usuario_Login");
            }
            else if (!Session["id"].ToString().Equals("0"))
            {
                Producto p = db.Productoes.Find(Int32.Parse(idProducto));

FerreteriaProMAX02/Views/Ventas/Create.cshtml
@model FerreteriaProMAX02.Models.Venta

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idPersona, "idPersona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idPersona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idEmpleado, "idEmpleado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEmpleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FerreteriaProMAX02/Views/Ventas/Delete.cshtml
@model FerreteriaProMAX02.Models.Venta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Venta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleado.IdEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Cedula)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FerreteriaProMAX02/Views/Ventas/Details.cshtml
@model FerreteriaProMAX02.Models.Venta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Venta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleado.IdEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Cedula)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdVenta }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FerreteriaProMAX02/Views/Ventas/Edit.cshtml
@model FerreteriaProMAX02.Models.Venta

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdVenta)

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idPersona, "idPersona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idPersona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idEmpleado, "idEmpleado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEmpleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FerreteriaProMAX02/Views/Ventas/Index.cshtml
@model IEnumerable<FerreteriaProMAX02.Models.Venta>

@{
    ViewBag.Title = "Index";
}

<h2>Buscar venta</h2>

<p>
    <a href="@Url.Action("Create")" class="btn btn btn-info">
        Crear Nuevo
        <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
    </a>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr class="steven">
        <th>
            <span>Fecha de Venta</span>
            @*@Html.DisplayNameFor(model => model.fecha)*@
        </th>
        <th>
            <span>Nombre Empleado</span>
            @*@Html.DisplayNameFor(model => model.Empleado)*@
        </th>
        <th>
          <span>Nombre del cliente</span>
           @* @Html.DisplayNameFor(model => model.Persona)*@
            </a>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empleado.Persona.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Persona.nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdVenta }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdVenta }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdVenta })
        </td>
    </tr>
}

</table>

FerreteriaProMAX02/Views/Ventas/VentaN.cshtml
@{
    ViewBag.Title = "VentaN";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/alertify.min.js"></script>
<link href="~/Content/alertify.core.css" rel="stylesheet" />
<link href="~/Content/alertify.default.css" rel="stylesheet" />

<h2>Nueva Venta</h2>

<script type="text/javascript">

    $(document).ready(function () {

        $("a[rel='pop-up']").click(function () {

            var caracteristicas = "height=550,width=1000,scrollTo,resizable=1,scrollbars=1,location=0";
            nueva = window.open(this.href, 'popup', caracteristicas);
            return false;
        });
        //botones
        $("#finalizar").click(function () {
            //alertify.alert("Boton Iniciado");
            //console.info('hola');
            var i = 0;
            var envio = "{fecha:'" + $("#id_fecha").val() + "',Cedula:'" + $("#idCliente").val() + "',idEmpleado:'" + $("#id_empleado").val() + "',Total1:'" + $("#TotalaPagar").val() + "',IdPago:'" + $("#idPago").val() + "',";
            $("#detalle tbody tr").each(function (index) {
                if (i == 0) {
                    envio += "ListadoDetalle:[{IdProducto:'" + $(this).find('td').eq(0).text() +
                        "',Cantidad:'" + $(this).find('td').eq(2).text() +
                        "',Descuento:'" + $(this).find('td').eq(4).text() +
                        "',SubTOTAL:'" + $(this).find('td').eq(5).text() + "'}";
                } else {
                    envio += ",{IdProducto:'" + $(this).find('td').eq(0).text() +
                        "',Cantidad:'" + $(this).find('td').eq(2).text() +
                        "',Descuento:'" + $(this).find('td').eq(4).text() +
                        "',SubTOTAL:'" + $(this).find('td').eq(5).text() + "'}"
                }
                i = 1;
            });
            envio += "]}";

            var json = eval("(" + envio + ')');

            //alertify.alert("INGRESE DATOS");
            console.info(json);

            $.ajax({
                url: "GuardarVenta",
                data: JSON.stringify(json),
                type: "POST",
                async: false,//this makes the ajax-call blocking
                contentType: 'application/json;charset=UTF-8',
                dataType: 'json',
                success: function (response) {
                    alertify.alert(response);
                    valid = response.valid;
                },
                error: function (error) {
                    alertify.alert(error);

                }
            });
        });

    });
    //variables
    var total = 0;
    var valor = 0;
    var subtotal = 0;
    function obtenerCliente(Cliente) {
        //var watchclose = setInterval(function () {
        $("#txtnombre").val(Cliente.DatosPersonales);
        $("#idCliente").val(Cliente.Identificacion);
        $("#codigoCliente").val(Cliente.Codigo);

        //});
    }

    function fn_agregar() {

        cadena = "<tr>"
        cadena = cadena + "<td>" + $("#idproducto").val() + "</td>";
        cadena = cadena + "<td>" + $("#nombreproducto").val() + "</td>";
        cadena = cadena + "<td>" + $("#cantidad").val() + "</td>";
        cadena = cadena + "<td>" + $("#precio").val() + "</td>";
        cadena = cadena + "<td>" + $("#descuento").val() + "</td>";

        var y = 0;
        var x = 0;
        var des = 0;
        y = $("#cantidad").val();
        x = $("#precio").val();
        des = $("#descuento").val();
        subtotal = (x * y) - des;
        cadena = cadena + "<td>" + subtotal + "</td>"
        cadena = cadena + "<td><a class ='elimina'><button class='btn btn-danger' type='button'><span class='fa fa-remove'></span></button></a></td>";
        $("#detalle tbody").append(cadena);
        sumar();
        fn_dar_eliminar();
        limpiar();
    };
    function limpiar() {
        $("#nombreproducto").val("");
        $("#idproducto").val("");
        $("#precio").val("");
        $("#ListaProducto").val("");
        $("#cantidad").val("");
        $("#descuento").val("");
    }
    function limpiarCliente() {
        $("#txtnombre").val("");
        $("#idCliente").val("");
        $("#codigoCliente").val("");
    }
    function limpiarDetalle() {
        $("#detalle tbody tr").val("");
    }
    function sumar() {
        total = total + subtotal;
        console.info(total);
        $("#TotalaPagar").val(total);

    }
    function restar() {
        total = total - valor;
        $("#TotalaPagar").val(total);
    }
    function fn_dar_eliminar() {
        $("a.elimina").click(function () {
            valor = $(this).parents("tr").find("td").eq(5).html();

            $(this).parents("tr").fadeOut("normal", function () {
                $(this).remove();
                restar();
            });
        });
    };


</script>
<table id="encabezado" class="table">
    <thead class="row">
        <tr style="font-size:20px;">
            @*<th>Id Venta <input style="color:red; font-size:12px;" class="form-control" type="text" id="id_venta" value="@ViewBag.IdVenta" readonly /></th>*@
            <th class="col">ID Empleado <input style="color:red; font-size:14px;" class="form-control" type="text" id="id_empleado" value="@ViewBag.IdEmpleado" readonly /></th>
            <th>
                Fecha
                <input style="color:red;font-size:20px;" class="form-control" type="text" id="id_fecha" readonly value="@DateTime.Now.Year-@DateTime.Now.Month-@DateTime.Now.Day @DateTime.Now.Hour:@DateTime.Now.Minute:@DateTime.Now.Second" />

            </th>
        </tr>
    </thead>
    <tbody>
        <tr style="font-size:20px;">
            <td>
                Detalles del Cliente
                <a href='@(Url.Action("ObtenerClientes", "Ventas"))' rel="pop-up">
                    <input class="btn btn-warning btn-lg col-md-12" type="button" name="enlace_cliente" value="Obtener Cliente" />
                </a>
            </td>
            <td>
                Modo de Pago
                <div class="col-md-12 dropdown">
                    @Html.DropDownList("idPago", null, "Seleccione Modo Pago", htmlAttributes: new { @class = "form-control", @required = "required" })
                    @*@Html.DropDownList("modoPago", ViewBag.ListaModoPago as SelectList, "Seleccione Modo Pago", htmlAttributes: new { @class = "form-control", @required = "required" })*@
                </div>
            </td>
        </tr>
        <tr style="font-size:20px;">

            <td>
                Nombre Cliente
                <input style="font-size:20px; font-weight:700;" class="form-control" type="text" id="txtnombre" readonly required />
            </td>
            <td>
                DNI
                <input type="hidden" id="codigoCliente">
                <input style="font-size:20px; font-weight:700;" class="form-control" type="text" id="idCliente" readonly required />
            </td>
        </tr>
        <tr style="font-size:20px;">
            <td style="float:right; vertical-align:middle;">Detalles del Producto</td>
            <td>
                @*<a class="btn_productos btn btn-primary" href="#">
                       Obtener Productos
                    </a>*@

                <div class="form-group col-md-12">
                    <div class="col-md-9 dropdown">
                        @Html.DropDownList("IdProductoL", null,"Seleccione un Producto", htmlAttributes: new { @class = "form-control", @required = "required" })
                        @*@Html.DropDownList("ListaProducto", ViewBag.ListaProducto as SelectList, "Seleccione un Producto", htmlAttributes: new { @class = "form-control" })*@
                    </div>
                    <div class="col-md-3">
                        <button class="btn btn-warning btn-lg" name="btnproductos" id="btnproductos">Seleccionar</button>
                    </div>
                </div>

            </td>
        </tr>
    </tbody>
</table>

<form action="javascript:fn_agregar()" ; method="post" id="frm_usu" class="form-horizontal">
    <table class="table">
        <tr style="font-size:20px;">
            <td>Nombre del Producto <input style="font-size:20px; font-weight:700;" class="form-control" type="text" id="nombreproducto" readonly required /></td>
            <td>Id <input style="font-size:20px; font-weight:700;" type="text" id="idproducto" class="form-control" readonly required /></td>
            <td>Precio <input style="font-size:20px; font-weight:700;" type="text" id="precio" class="form-control" readonly required /></td>
            <td>Descuento <input style="font-size:20px; font-weight:700;" class="form-control" type="number" id="descuento" value="0" onfocus="this.value = '';" required /></td>
            <td>Cantidad <input style="font-size:20px; font-weight:700;" class="form-control" type="number" id="cantidad" value="Ingrese Cantidad" onfocus="this.value = '';" required /></td>
            <td colspan="2"><input class="btn btn-primary btn-lg" type="submit" name="agregar" id="agregar" value="Agregar" /></td>
        </tr>
    </table>
</form>
<table id="detalle" class="lista table" border="1">
    <thead style="font-size:18px;">
        <tr class="bg-success">
            <td>Detalle de la Compra</td>
        </tr>
        <tr class="bg-danger">
            <th>Id</th>
            <th>Descripcion del Producto</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Descuento</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody></tbody>

</table>
<table class="table">
    <tr>
        <td style="float:right;font-size:20px;">Total a Pagar</td>
        <th></th>
        <td><input style="font-size:20px; font-weight:700;" class="form-control" type="text" name="TotalaPagar" id="TotalaPagar" required readonly /></td>
    </tr>
</table>
<input class="btn btn-success btn-lg" type="button" id="finalizar" value="Guardar Venta" />
<input class="btn btn-success btn-lg" type="button" id="txtnueva" value="Nueva" />


<script>
    $(document).ready(function () {
        $("#txtnueva").click(function () {
            $.ajax({
                success: function (res) {
                    //alertify.alert("exito");
                    window.location.reload().ajax();
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function () {
        $("#btnproductos").click(function () {
            $.ajax({
                type: "POST",
                url: "Seleccionar",
                data: { idProducto: $("#IdProductoL").val() },
                dataType: 'json',
                success: function (mensaje) {
                    //alert(mensaje);
                    //$("#idproducto").val(mensaje.Nombre);
                    $(mensaje).each(function (index, item) {
                        //recibir datos json
                        $("#idproducto").val(item.IdProducto);
                        $("#nombreproducto").val(item.Nombre);
                        $("#precio").val(item.PrecioU);
                    });
                }
            });
        });
    });

</script>